// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MapReduce.proto

#include "MapReduce.pb.h"
#include "MapReduce.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mapreduce {

static const char* MapReduce_method_names[] = {
  "/mapreduce.MapReduce/Map",
  "/mapreduce.MapReduce/Reduce",
  "/mapreduce.MapReduce/SubscribeReduceTask",
  "/mapreduce.MapReduce/SubscribeMapTask",
  "/mapreduce.MapReduce/MapDone",
  "/mapreduce.MapReduce/ReduceDone",
};

std::unique_ptr< MapReduce::Stub> MapReduce::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MapReduce::Stub> stub(new MapReduce::Stub(channel, options));
  return stub;
}

MapReduce::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Map_(MapReduce_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Reduce_(MapReduce_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubscribeReduceTask_(MapReduce_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SubscribeMapTask_(MapReduce_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_MapDone_(MapReduce_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReduceDone_(MapReduce_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MapReduce::Stub::Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::mapreduce::MapResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mapreduce::MapRequest, ::mapreduce::MapResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Map_, context, request, response);
}

void MapReduce::Stub::async::Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mapreduce::MapRequest, ::mapreduce::MapResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Map_, context, request, response, std::move(f));
}

void MapReduce::Stub::async::Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Map_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>* MapReduce::Stub::PrepareAsyncMapRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mapreduce::MapResponse, ::mapreduce::MapRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Map_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>* MapReduce::Stub::AsyncMapRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMapRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MapReduce::Stub::Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::mapreduce::ReduceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Reduce_, context, request, response);
}

void MapReduce::Stub::async::Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reduce_, context, request, response, std::move(f));
}

void MapReduce::Stub::async::Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reduce_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>* MapReduce::Stub::PrepareAsyncReduceRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mapreduce::ReduceResponse, ::mapreduce::ReduceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Reduce_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>* MapReduce::Stub::AsyncReduceRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReduceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::mapreduce::TaskNotification>* MapReduce::Stub::SubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::mapreduce::TaskNotification>::Create(channel_.get(), rpcmethod_SubscribeReduceTask_, context, request);
}

void MapReduce::Stub::async::SubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::mapreduce::TaskNotification>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::mapreduce::TaskNotification>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeReduceTask_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* MapReduce::Stub::AsyncSubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mapreduce::TaskNotification>::Create(channel_.get(), cq, rpcmethod_SubscribeReduceTask_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* MapReduce::Stub::PrepareAsyncSubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mapreduce::TaskNotification>::Create(channel_.get(), cq, rpcmethod_SubscribeReduceTask_, context, request, false, nullptr);
}

::grpc::ClientReader< ::mapreduce::TaskNotification>* MapReduce::Stub::SubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::mapreduce::TaskNotification>::Create(channel_.get(), rpcmethod_SubscribeMapTask_, context, request);
}

void MapReduce::Stub::async::SubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::mapreduce::TaskNotification>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::mapreduce::TaskNotification>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeMapTask_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* MapReduce::Stub::AsyncSubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mapreduce::TaskNotification>::Create(channel_.get(), cq, rpcmethod_SubscribeMapTask_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* MapReduce::Stub::PrepareAsyncSubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mapreduce::TaskNotification>::Create(channel_.get(), cq, rpcmethod_SubscribeMapTask_, context, request, false, nullptr);
}

::grpc::Status MapReduce::Stub::MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mapreduce::MapRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MapDone_, context, request, response);
}

void MapReduce::Stub::async::MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mapreduce::MapRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MapDone_, context, request, response, std::move(f));
}

void MapReduce::Stub::async::MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MapDone_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* MapReduce::Stub::PrepareAsyncMapDoneRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::mapreduce::MapRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MapDone_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* MapReduce::Stub::AsyncMapDoneRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMapDoneRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MapReduce::Stub::ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mapreduce::ReduceRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReduceDone_, context, request, response);
}

void MapReduce::Stub::async::ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mapreduce::ReduceRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReduceDone_, context, request, response, std::move(f));
}

void MapReduce::Stub::async::ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReduceDone_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* MapReduce::Stub::PrepareAsyncReduceDoneRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::mapreduce::ReduceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReduceDone_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* MapReduce::Stub::AsyncReduceDoneRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReduceDoneRaw(context, request, cq);
  result->StartCall();
  return result;
}

MapReduce::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduce_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduce::Service, ::mapreduce::MapRequest, ::mapreduce::MapResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MapReduce::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mapreduce::MapRequest* req,
             ::mapreduce::MapResponse* resp) {
               return service->Map(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduce_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduce::Service, ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MapReduce::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mapreduce::ReduceRequest* req,
             ::mapreduce::ReduceResponse* resp) {
               return service->Reduce(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduce_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MapReduce::Service, ::google::protobuf::Empty, ::mapreduce::TaskNotification>(
          [](MapReduce::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::mapreduce::TaskNotification>* writer) {
               return service->SubscribeReduceTask(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduce_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MapReduce::Service, ::google::protobuf::Empty, ::mapreduce::TaskNotification>(
          [](MapReduce::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::mapreduce::TaskNotification>* writer) {
               return service->SubscribeMapTask(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduce_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduce::Service, ::mapreduce::MapRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MapReduce::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mapreduce::MapRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->MapDone(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduce_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduce::Service, ::mapreduce::ReduceRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MapReduce::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mapreduce::ReduceRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->ReduceDone(ctx, req, resp);
             }, this)));
}

MapReduce::Service::~Service() {
}

::grpc::Status MapReduce::Service::Map(::grpc::ServerContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduce::Service::Reduce(::grpc::ServerContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduce::Service::SubscribeReduceTask(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduce::Service::SubscribeMapTask(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduce::Service::MapDone(::grpc::ServerContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduce::Service::ReduceDone(::grpc::ServerContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mapreduce

