// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MapReduce.proto
// Protobuf C++ Version: 6.30.0

#include "MapReduce.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mapreduce {

inline constexpr TaskNotification::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        task_type_{static_cast< ::mapreduce::TaskNotification_TaskType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR TaskNotification::TaskNotification(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TaskNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TaskNotificationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskNotificationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskNotificationDefaultTypeInternal() {}
  union {
    TaskNotification _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskNotificationDefaultTypeInternal _TaskNotification_default_instance_;

inline constexpr ReduceResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_finished_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ReduceResponse::ReduceResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReduceResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReduceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReduceResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReduceResponseDefaultTypeInternal() {}
  union {
    ReduceResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReduceResponseDefaultTypeInternal _ReduceResponse_default_instance_;

inline constexpr ReduceRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reduce_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReduceRequest::ReduceRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReduceRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReduceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReduceRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReduceRequestDefaultTypeInternal() {}
  union {
    ReduceRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReduceRequestDefaultTypeInternal _ReduceRequest_default_instance_;

inline constexpr MapResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_finished_{false} {}

template <typename>
PROTOBUF_CONSTEXPR MapResponse::MapResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MapResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MapResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapResponseDefaultTypeInternal() {}
  union {
    MapResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapResponseDefaultTypeInternal _MapResponse_default_instance_;

inline constexpr MapRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        map_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MapRequest::MapRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MapRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MapRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapRequestDefaultTypeInternal() {}
  union {
    MapRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapRequestDefaultTypeInternal _MapRequest_default_instance_;

inline constexpr KeyValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_{0} {}

template <typename>
PROTOBUF_CONSTEXPR KeyValue::KeyValue(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(KeyValue_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct KeyValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeyValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyValueDefaultTypeInternal() {}
  union {
    KeyValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyValueDefaultTypeInternal _KeyValue_default_instance_;
}  // namespace mapreduce
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_MapReduce_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_MapReduce_2eproto = nullptr;
const ::uint32_t
    TableStruct_MapReduce_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::mapreduce::TaskNotification, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::TaskNotification, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mapreduce::TaskNotification, _impl_.task_type_),
        0,
        PROTOBUF_FIELD_OFFSET(::mapreduce::KeyValue, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::KeyValue, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mapreduce::KeyValue, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::KeyValue, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::mapreduce::MapRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::MapRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mapreduce::MapRequest, _impl_.map_id_),
        0,
        PROTOBUF_FIELD_OFFSET(::mapreduce::MapResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::MapResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mapreduce::MapResponse, _impl_.is_finished_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::MapResponse, _impl_.filename_),
        1,
        0,
        PROTOBUF_FIELD_OFFSET(::mapreduce::ReduceRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::ReduceRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mapreduce::ReduceRequest, _impl_.reduce_id_),
        0,
        PROTOBUF_FIELD_OFFSET(::mapreduce::ReduceResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::ReduceResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mapreduce::ReduceResponse, _impl_.is_finished_),
        PROTOBUF_FIELD_OFFSET(::mapreduce::ReduceResponse, _impl_.filename_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::mapreduce::TaskNotification)},
        {10, 20, -1, sizeof(::mapreduce::KeyValue)},
        {22, 31, -1, sizeof(::mapreduce::MapRequest)},
        {32, 42, -1, sizeof(::mapreduce::MapResponse)},
        {44, 53, -1, sizeof(::mapreduce::ReduceRequest)},
        {54, 64, -1, sizeof(::mapreduce::ReduceResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::mapreduce::_TaskNotification_default_instance_._instance,
    &::mapreduce::_KeyValue_default_instance_._instance,
    &::mapreduce::_MapRequest_default_instance_._instance,
    &::mapreduce::_MapResponse_default_instance_._instance,
    &::mapreduce::_ReduceRequest_default_instance_._instance,
    &::mapreduce::_ReduceResponse_default_instance_._instance,
};
const char descriptor_table_protodef_MapReduce_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017MapReduce.proto\022\tmapreduce\032\033google/pro"
    "tobuf/empty.proto\"v\n\020TaskNotification\0227\n"
    "\ttask_type\030\001 \001(\0162$.mapreduce.TaskNotific"
    "ation.TaskType\")\n\010TaskType\022\010\n\004NONE\020\000\022\007\n\003"
    "MAP\020\001\022\n\n\006REDUCE\020\002\"&\n\010KeyValue\022\013\n\003key\030\001 \001"
    "(\t\022\r\n\005value\030\002 \001(\005\"\034\n\nMapRequest\022\016\n\006map_i"
    "d\030\001 \001(\005\"4\n\013MapResponse\022\023\n\013is_finished\030\001 "
    "\001(\010\022\020\n\010filename\030\002 \001(\t\"\"\n\rReduceRequest\022\021"
    "\n\treduce_id\030\001 \001(\005\"7\n\016ReduceResponse\022\023\n\013i"
    "s_finished\030\001 \001(\010\022\020\n\010filename\030\002 \001(\t2\223\003\n\tM"
    "apReduce\0224\n\003Map\022\025.mapreduce.MapRequest\032\026"
    ".mapreduce.MapResponse\022=\n\006Reduce\022\030.mapre"
    "duce.ReduceRequest\032\031.mapreduce.ReduceRes"
    "ponse\022L\n\023SubscribeReduceTask\022\026.google.pr"
    "otobuf.Empty\032\033.mapreduce.TaskNotificatio"
    "n0\001\022I\n\020SubscribeMapTask\022\026.google.protobu"
    "f.Empty\032\033.mapreduce.TaskNotification0\001\0228"
    "\n\007MapDone\022\025.mapreduce.MapRequest\032\026.googl"
    "e.protobuf.Empty\022>\n\nReduceDone\022\030.mapredu"
    "ce.ReduceRequest\032\026.google.protobuf.Empty"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_MapReduce_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_MapReduce_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MapReduce_2eproto = {
    false,
    false,
    808,
    descriptor_table_protodef_MapReduce_2eproto,
    "MapReduce.proto",
    &descriptor_table_MapReduce_2eproto_once,
    descriptor_table_MapReduce_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_MapReduce_2eproto::offsets,
    file_level_enum_descriptors_MapReduce_2eproto,
    file_level_service_descriptors_MapReduce_2eproto,
};
namespace mapreduce {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TaskNotification_TaskType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MapReduce_2eproto);
  return file_level_enum_descriptors_MapReduce_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TaskNotification_TaskType_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class TaskNotification::_Internal {
 public:
  using HasBits =
      decltype(std::declval<TaskNotification>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TaskNotification, _impl_._has_bits_);
};

TaskNotification::TaskNotification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TaskNotification_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mapreduce.TaskNotification)
}
TaskNotification::TaskNotification(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TaskNotification& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TaskNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE TaskNotification::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void TaskNotification::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.task_type_ = {};
}
TaskNotification::~TaskNotification() {
  // @@protoc_insertion_point(destructor:mapreduce.TaskNotification)
  SharedDtor(*this);
}
inline void TaskNotification::SharedDtor(MessageLite& self) {
  TaskNotification& this_ = static_cast<TaskNotification&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TaskNotification::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TaskNotification(arena);
}
constexpr auto TaskNotification::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TaskNotification),
                                            alignof(TaskNotification));
}
constexpr auto TaskNotification::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TaskNotification_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TaskNotification::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TaskNotification>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TaskNotification::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TaskNotification>(), &TaskNotification::ByteSizeLong,
              &TaskNotification::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TaskNotification, _impl_._cached_size_),
          false,
      },
      &TaskNotification::kDescriptorMethods,
      &descriptor_table_MapReduce_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        TaskNotification_class_data_ =
            TaskNotification::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL TaskNotification::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TaskNotification_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TaskNotification_class_data_.tc_table);
  return TaskNotification_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
TaskNotification::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TaskNotification, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TaskNotification_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mapreduce::TaskNotification>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .mapreduce.TaskNotification.TaskType task_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TaskNotification, _impl_.task_type_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(TaskNotification, _impl_.task_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .mapreduce.TaskNotification.TaskType task_type = 1;
    {PROTOBUF_FIELD_OFFSET(TaskNotification, _impl_.task_type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TaskNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.TaskNotification)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.task_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TaskNotification::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TaskNotification& this_ = static_cast<const TaskNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TaskNotification::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TaskNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.TaskNotification)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .mapreduce.TaskNotification.TaskType task_type = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_task_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_task_type(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.TaskNotification)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TaskNotification::ByteSizeLong(const MessageLite& base) {
  const TaskNotification& this_ = static_cast<const TaskNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TaskNotification::ByteSizeLong() const {
  const TaskNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mapreduce.TaskNotification)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .mapreduce.TaskNotification.TaskType task_type = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_task_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_task_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TaskNotification::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TaskNotification*>(&to_msg);
  auto& from = static_cast<const TaskNotification&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.TaskNotification)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_task_type() != 0) {
      _this->_impl_.task_type_ = from._impl_.task_type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TaskNotification::CopyFrom(const TaskNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.TaskNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TaskNotification::InternalSwap(TaskNotification* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.task_type_, other->_impl_.task_type_);
}

::google::protobuf::Metadata TaskNotification::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class KeyValue::_Internal {
 public:
  using HasBits =
      decltype(std::declval<KeyValue>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(KeyValue, _impl_._has_bits_);
};

KeyValue::KeyValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, KeyValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mapreduce.KeyValue)
}
PROTOBUF_NDEBUG_INLINE KeyValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::mapreduce::KeyValue& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_) {}

KeyValue::KeyValue(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const KeyValue& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, KeyValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  KeyValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.value_ = from._impl_.value_;

  // @@protoc_insertion_point(copy_constructor:mapreduce.KeyValue)
}
PROTOBUF_NDEBUG_INLINE KeyValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena) {}

inline void KeyValue::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
KeyValue::~KeyValue() {
  // @@protoc_insertion_point(destructor:mapreduce.KeyValue)
  SharedDtor(*this);
}
inline void KeyValue::SharedDtor(MessageLite& self) {
  KeyValue& this_ = static_cast<KeyValue&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL KeyValue::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) KeyValue(arena);
}
constexpr auto KeyValue::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(KeyValue),
                                            alignof(KeyValue));
}
constexpr auto KeyValue::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_KeyValue_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &KeyValue::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<KeyValue>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &KeyValue::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<KeyValue>(), &KeyValue::ByteSizeLong,
              &KeyValue::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(KeyValue, _impl_._cached_size_),
          false,
      },
      &KeyValue::kDescriptorMethods,
      &descriptor_table_MapReduce_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        KeyValue_class_data_ =
            KeyValue::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL KeyValue::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&KeyValue_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(KeyValue_class_data_.tc_table);
  return KeyValue_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2>
KeyValue::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(KeyValue, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    KeyValue_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mapreduce::KeyValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(KeyValue, _impl_.value_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(KeyValue, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(KeyValue, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(KeyValue, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(KeyValue, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\22\3\0\0\0\0\0\0"
    "mapreduce.KeyValue"
    "key"
  }},
};
PROTOBUF_NOINLINE void KeyValue::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.KeyValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.key_.ClearNonDefaultToEmpty();
  }
  _impl_.value_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL KeyValue::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const KeyValue& this_ = static_cast<const KeyValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL KeyValue::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const KeyValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.KeyValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string key = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_key().empty()) {
      const std::string& _s = this_._internal_key();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mapreduce.KeyValue.key");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 value = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_value() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.KeyValue)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t KeyValue::ByteSizeLong(const MessageLite& base) {
  const KeyValue& this_ = static_cast<const KeyValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t KeyValue::ByteSizeLong() const {
  const KeyValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mapreduce.KeyValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string key = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_key().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_key());
      }
    }
    // int32 value = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_value() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void KeyValue::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<KeyValue*>(&to_msg);
  auto& from = static_cast<const KeyValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.KeyValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_key().empty()) {
        _this->_internal_set_key(from._internal_key());
      } else {
        if (_this->_impl_.key_.IsDefault()) {
          _this->_internal_set_key("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_value() != 0) {
        _this->_impl_.value_ = from._impl_.value_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void KeyValue::CopyFrom(const KeyValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.KeyValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void KeyValue::InternalSwap(KeyValue* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata KeyValue::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MapRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MapRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MapRequest, _impl_._has_bits_);
};

MapRequest::MapRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MapRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mapreduce.MapRequest)
}
MapRequest::MapRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MapRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MapRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE MapRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void MapRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.map_id_ = {};
}
MapRequest::~MapRequest() {
  // @@protoc_insertion_point(destructor:mapreduce.MapRequest)
  SharedDtor(*this);
}
inline void MapRequest::SharedDtor(MessageLite& self) {
  MapRequest& this_ = static_cast<MapRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MapRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MapRequest(arena);
}
constexpr auto MapRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MapRequest),
                                            alignof(MapRequest));
}
constexpr auto MapRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MapRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MapRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MapRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MapRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MapRequest>(), &MapRequest::ByteSizeLong,
              &MapRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MapRequest, _impl_._cached_size_),
          false,
      },
      &MapRequest::kDescriptorMethods,
      &descriptor_table_MapReduce_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        MapRequest_class_data_ =
            MapRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL MapRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MapRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MapRequest_class_data_.tc_table);
  return MapRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
MapRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MapRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MapRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mapreduce::MapRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 map_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MapRequest, _impl_.map_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(MapRequest, _impl_.map_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 map_id = 1;
    {PROTOBUF_FIELD_OFFSET(MapRequest, _impl_.map_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void MapRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.MapRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.map_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MapRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MapRequest& this_ = static_cast<const MapRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MapRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MapRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.MapRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 map_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_map_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_map_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.MapRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MapRequest::ByteSizeLong(const MessageLite& base) {
  const MapRequest& this_ = static_cast<const MapRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MapRequest::ByteSizeLong() const {
  const MapRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mapreduce.MapRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 map_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_map_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_map_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MapRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MapRequest*>(&to_msg);
  auto& from = static_cast<const MapRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.MapRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_map_id() != 0) {
      _this->_impl_.map_id_ = from._impl_.map_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MapRequest::CopyFrom(const MapRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.MapRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MapRequest::InternalSwap(MapRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.map_id_, other->_impl_.map_id_);
}

::google::protobuf::Metadata MapRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MapResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MapResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MapResponse, _impl_._has_bits_);
};

MapResponse::MapResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MapResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mapreduce.MapResponse)
}
PROTOBUF_NDEBUG_INLINE MapResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::mapreduce::MapResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filename_(arena, from.filename_) {}

MapResponse::MapResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MapResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MapResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MapResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.is_finished_ = from._impl_.is_finished_;

  // @@protoc_insertion_point(copy_constructor:mapreduce.MapResponse)
}
PROTOBUF_NDEBUG_INLINE MapResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        filename_(arena) {}

inline void MapResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_finished_ = {};
}
MapResponse::~MapResponse() {
  // @@protoc_insertion_point(destructor:mapreduce.MapResponse)
  SharedDtor(*this);
}
inline void MapResponse::SharedDtor(MessageLite& self) {
  MapResponse& this_ = static_cast<MapResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MapResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MapResponse(arena);
}
constexpr auto MapResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MapResponse),
                                            alignof(MapResponse));
}
constexpr auto MapResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MapResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MapResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MapResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MapResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MapResponse>(), &MapResponse::ByteSizeLong,
              &MapResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MapResponse, _impl_._cached_size_),
          false,
      },
      &MapResponse::kDescriptorMethods,
      &descriptor_table_MapReduce_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        MapResponse_class_data_ =
            MapResponse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL MapResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MapResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MapResponse_class_data_.tc_table);
  return MapResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2>
MapResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MapResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MapResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mapreduce::MapResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string filename = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(MapResponse, _impl_.filename_)}},
    // bool is_finished = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MapResponse, _impl_.is_finished_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(MapResponse, _impl_.is_finished_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_finished = 1;
    {PROTOBUF_FIELD_OFFSET(MapResponse, _impl_.is_finished_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string filename = 2;
    {PROTOBUF_FIELD_OFFSET(MapResponse, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\0\10\0\0\0\0\0"
    "mapreduce.MapResponse"
    "filename"
  }},
};
PROTOBUF_NOINLINE void MapResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.MapResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.filename_.ClearNonDefaultToEmpty();
  }
  _impl_.is_finished_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MapResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MapResponse& this_ = static_cast<const MapResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MapResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MapResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.MapResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool is_finished = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_is_finished() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_is_finished(), target);
    }
  }

  // string filename = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_filename().empty()) {
      const std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mapreduce.MapResponse.filename");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.MapResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MapResponse::ByteSizeLong(const MessageLite& base) {
  const MapResponse& this_ = static_cast<const MapResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MapResponse::ByteSizeLong() const {
  const MapResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mapreduce.MapResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string filename = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // bool is_finished = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_is_finished() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MapResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MapResponse*>(&to_msg);
  auto& from = static_cast<const MapResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.MapResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_is_finished() != 0) {
        _this->_impl_.is_finished_ = from._impl_.is_finished_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MapResponse::CopyFrom(const MapResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.MapResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MapResponse::InternalSwap(MapResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  swap(_impl_.is_finished_, other->_impl_.is_finished_);
}

::google::protobuf::Metadata MapResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReduceRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ReduceRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReduceRequest, _impl_._has_bits_);
};

ReduceRequest::ReduceRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReduceRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mapreduce.ReduceRequest)
}
ReduceRequest::ReduceRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReduceRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReduceRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ReduceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ReduceRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.reduce_id_ = {};
}
ReduceRequest::~ReduceRequest() {
  // @@protoc_insertion_point(destructor:mapreduce.ReduceRequest)
  SharedDtor(*this);
}
inline void ReduceRequest::SharedDtor(MessageLite& self) {
  ReduceRequest& this_ = static_cast<ReduceRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReduceRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReduceRequest(arena);
}
constexpr auto ReduceRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReduceRequest),
                                            alignof(ReduceRequest));
}
constexpr auto ReduceRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReduceRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReduceRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReduceRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReduceRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReduceRequest>(), &ReduceRequest::ByteSizeLong,
              &ReduceRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReduceRequest, _impl_._cached_size_),
          false,
      },
      &ReduceRequest::kDescriptorMethods,
      &descriptor_table_MapReduce_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ReduceRequest_class_data_ =
            ReduceRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ReduceRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReduceRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReduceRequest_class_data_.tc_table);
  return ReduceRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ReduceRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReduceRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReduceRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mapreduce::ReduceRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 reduce_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReduceRequest, _impl_.reduce_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(ReduceRequest, _impl_.reduce_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 reduce_id = 1;
    {PROTOBUF_FIELD_OFFSET(ReduceRequest, _impl_.reduce_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ReduceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.ReduceRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reduce_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReduceRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReduceRequest& this_ = static_cast<const ReduceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReduceRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReduceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.ReduceRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 reduce_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_reduce_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_reduce_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.ReduceRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReduceRequest::ByteSizeLong(const MessageLite& base) {
  const ReduceRequest& this_ = static_cast<const ReduceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReduceRequest::ByteSizeLong() const {
  const ReduceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mapreduce.ReduceRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 reduce_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_reduce_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_reduce_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReduceRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReduceRequest*>(&to_msg);
  auto& from = static_cast<const ReduceRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.ReduceRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_reduce_id() != 0) {
      _this->_impl_.reduce_id_ = from._impl_.reduce_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReduceRequest::CopyFrom(const ReduceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.ReduceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReduceRequest::InternalSwap(ReduceRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.reduce_id_, other->_impl_.reduce_id_);
}

::google::protobuf::Metadata ReduceRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReduceResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ReduceResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReduceResponse, _impl_._has_bits_);
};

ReduceResponse::ReduceResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReduceResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mapreduce.ReduceResponse)
}
PROTOBUF_NDEBUG_INLINE ReduceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::mapreduce::ReduceResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filename_(arena, from.filename_) {}

ReduceResponse::ReduceResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReduceResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReduceResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReduceResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.is_finished_ = from._impl_.is_finished_;

  // @@protoc_insertion_point(copy_constructor:mapreduce.ReduceResponse)
}
PROTOBUF_NDEBUG_INLINE ReduceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        filename_(arena) {}

inline void ReduceResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_finished_ = {};
}
ReduceResponse::~ReduceResponse() {
  // @@protoc_insertion_point(destructor:mapreduce.ReduceResponse)
  SharedDtor(*this);
}
inline void ReduceResponse::SharedDtor(MessageLite& self) {
  ReduceResponse& this_ = static_cast<ReduceResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReduceResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReduceResponse(arena);
}
constexpr auto ReduceResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReduceResponse),
                                            alignof(ReduceResponse));
}
constexpr auto ReduceResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReduceResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReduceResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReduceResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReduceResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReduceResponse>(), &ReduceResponse::ByteSizeLong,
              &ReduceResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReduceResponse, _impl_._cached_size_),
          false,
      },
      &ReduceResponse::kDescriptorMethods,
      &descriptor_table_MapReduce_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ReduceResponse_class_data_ =
            ReduceResponse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ReduceResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReduceResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReduceResponse_class_data_.tc_table);
  return ReduceResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2>
ReduceResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReduceResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReduceResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mapreduce::ReduceResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string filename = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ReduceResponse, _impl_.filename_)}},
    // bool is_finished = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ReduceResponse, _impl_.is_finished_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(ReduceResponse, _impl_.is_finished_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_finished = 1;
    {PROTOBUF_FIELD_OFFSET(ReduceResponse, _impl_.is_finished_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string filename = 2;
    {PROTOBUF_FIELD_OFFSET(ReduceResponse, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\0\10\0\0\0\0\0"
    "mapreduce.ReduceResponse"
    "filename"
  }},
};
PROTOBUF_NOINLINE void ReduceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.ReduceResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.filename_.ClearNonDefaultToEmpty();
  }
  _impl_.is_finished_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReduceResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReduceResponse& this_ = static_cast<const ReduceResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReduceResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReduceResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.ReduceResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool is_finished = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_is_finished() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_is_finished(), target);
    }
  }

  // string filename = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_filename().empty()) {
      const std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mapreduce.ReduceResponse.filename");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.ReduceResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReduceResponse::ByteSizeLong(const MessageLite& base) {
  const ReduceResponse& this_ = static_cast<const ReduceResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReduceResponse::ByteSizeLong() const {
  const ReduceResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mapreduce.ReduceResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string filename = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // bool is_finished = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_is_finished() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReduceResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReduceResponse*>(&to_msg);
  auto& from = static_cast<const ReduceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.ReduceResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_is_finished() != 0) {
        _this->_impl_.is_finished_ = from._impl_.is_finished_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReduceResponse::CopyFrom(const ReduceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.ReduceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReduceResponse::InternalSwap(ReduceResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  swap(_impl_.is_finished_, other->_impl_.is_finished_);
}

::google::protobuf::Metadata ReduceResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace mapreduce
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_MapReduce_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
