// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MapReduce.proto
// Original file comments:
// 使用protoc3 语法
#ifndef GRPC_MapReduce_2eproto__INCLUDED
#define GRPC_MapReduce_2eproto__INCLUDED

#include "MapReduce.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace mapreduce {

//
//       定义MapReduce服务
//
class MapReduce final {
 public:
  static constexpr char const* service_full_name() {
    return "mapreduce.MapReduce";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Map函数
    virtual ::grpc::Status Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::mapreduce::MapResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::MapResponse>> AsyncMap(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::MapResponse>>(AsyncMapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::MapResponse>> PrepareAsyncMap(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::MapResponse>>(PrepareAsyncMapRaw(context, request, cq));
    }
    // Reduce函数
    virtual ::grpc::Status Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::mapreduce::ReduceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::ReduceResponse>> AsyncReduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::ReduceResponse>>(AsyncReduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::ReduceResponse>> PrepareAsyncReduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::ReduceResponse>>(PrepareAsyncReduceRaw(context, request, cq));
    }
    // 建立长连接， Master推送Map任务更新
    std::unique_ptr< ::grpc::ClientReaderInterface< ::mapreduce::TaskNotification>> SubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::mapreduce::TaskNotification>>(SubscribeReduceTaskRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>> AsyncSubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>>(AsyncSubscribeReduceTaskRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>> PrepareAsyncSubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>>(PrepareAsyncSubscribeReduceTaskRaw(context, request, cq));
    }
    // 建立长连接， Master推送Reduce任务更新
    std::unique_ptr< ::grpc::ClientReaderInterface< ::mapreduce::TaskNotification>> SubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::mapreduce::TaskNotification>>(SubscribeMapTaskRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>> AsyncSubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>>(AsyncSubscribeMapTaskRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>> PrepareAsyncSubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>>(PrepareAsyncSubscribeMapTaskRaw(context, request, cq));
    }
    // MapReduce任务完成
    virtual ::grpc::Status MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncMapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncMapDoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncMapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncMapDoneRaw(context, request, cq));
    }
    // Reduce任务完成
    virtual ::grpc::Status ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncReduceDoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncReduceDoneRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Map函数
      virtual void Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Reduce函数
      virtual void Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 建立长连接， Master推送Map任务更新
      virtual void SubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::mapreduce::TaskNotification>* reactor) = 0;
      // 建立长连接， Master推送Reduce任务更新
      virtual void SubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::mapreduce::TaskNotification>* reactor) = 0;
      // MapReduce任务完成
      virtual void MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Reduce任务完成
      virtual void ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::MapResponse>* AsyncMapRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::MapResponse>* PrepareAsyncMapRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::ReduceResponse>* AsyncReduceRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mapreduce::ReduceResponse>* PrepareAsyncReduceRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::mapreduce::TaskNotification>* SubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>* AsyncSubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>* PrepareAsyncSubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::mapreduce::TaskNotification>* SubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>* AsyncSubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mapreduce::TaskNotification>* PrepareAsyncSubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncMapDoneRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncMapDoneRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncReduceDoneRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncReduceDoneRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::mapreduce::MapResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>> AsyncMap(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>>(AsyncMapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>> PrepareAsyncMap(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>>(PrepareAsyncMapRaw(context, request, cq));
    }
    ::grpc::Status Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::mapreduce::ReduceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>> AsyncReduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>>(AsyncReduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>> PrepareAsyncReduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>>(PrepareAsyncReduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::mapreduce::TaskNotification>> SubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::mapreduce::TaskNotification>>(SubscribeReduceTaskRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>> AsyncSubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>>(AsyncSubscribeReduceTaskRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>> PrepareAsyncSubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>>(PrepareAsyncSubscribeReduceTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::mapreduce::TaskNotification>> SubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::mapreduce::TaskNotification>>(SubscribeMapTaskRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>> AsyncSubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>>(AsyncSubscribeMapTaskRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>> PrepareAsyncSubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>>(PrepareAsyncSubscribeMapTaskRaw(context, request, cq));
    }
    ::grpc::Status MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncMapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncMapDoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncMapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncMapDoneRaw(context, request, cq));
    }
    ::grpc::Status ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncReduceDoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncReduceDoneRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response, std::function<void(::grpc::Status)>) override;
      void Map(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response, std::function<void(::grpc::Status)>) override;
      void Reduce(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SubscribeReduceTask(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::mapreduce::TaskNotification>* reactor) override;
      void SubscribeMapTask(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::mapreduce::TaskNotification>* reactor) override;
      void MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void MapDone(::grpc::ClientContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void ReduceDone(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>* AsyncMapRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mapreduce::MapResponse>* PrepareAsyncMapRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>* AsyncReduceRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mapreduce::ReduceResponse>* PrepareAsyncReduceRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::mapreduce::TaskNotification>* SubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) override;
    ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* AsyncSubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* PrepareAsyncSubscribeReduceTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::mapreduce::TaskNotification>* SubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) override;
    ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* AsyncSubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::mapreduce::TaskNotification>* PrepareAsyncSubscribeMapTaskRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncMapDoneRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncMapDoneRaw(::grpc::ClientContext* context, const ::mapreduce::MapRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncReduceDoneRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncReduceDoneRaw(::grpc::ClientContext* context, const ::mapreduce::ReduceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Map_;
    const ::grpc::internal::RpcMethod rpcmethod_Reduce_;
    const ::grpc::internal::RpcMethod rpcmethod_SubscribeReduceTask_;
    const ::grpc::internal::RpcMethod rpcmethod_SubscribeMapTask_;
    const ::grpc::internal::RpcMethod rpcmethod_MapDone_;
    const ::grpc::internal::RpcMethod rpcmethod_ReduceDone_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Map函数
    virtual ::grpc::Status Map(::grpc::ServerContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response);
    // Reduce函数
    virtual ::grpc::Status Reduce(::grpc::ServerContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response);
    // 建立长连接， Master推送Map任务更新
    virtual ::grpc::Status SubscribeReduceTask(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* writer);
    // 建立长连接， Master推送Reduce任务更新
    virtual ::grpc::Status SubscribeMapTask(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* writer);
    // MapReduce任务完成
    virtual ::grpc::Status MapDone(::grpc::ServerContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response);
    // Reduce任务完成
    virtual ::grpc::Status ReduceDone(::grpc::ServerContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Map() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::mapreduce::MapResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMap(::grpc::ServerContext* context, ::mapreduce::MapRequest* request, ::grpc::ServerAsyncResponseWriter< ::mapreduce::MapResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Reduce() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::mapreduce::ReduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReduce(::grpc::ServerContext* context, ::mapreduce::ReduceRequest* request, ::grpc::ServerAsyncResponseWriter< ::mapreduce::ReduceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubscribeReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubscribeReduceTask() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SubscribeReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeReduceTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeReduceTask(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncWriter< ::mapreduce::TaskNotification>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubscribeMapTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubscribeMapTask() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_SubscribeMapTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMapTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeMapTask(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncWriter< ::mapreduce::TaskNotification>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_MapDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MapDone() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_MapDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapDone(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapDone(::grpc::ServerContext* context, ::mapreduce::MapRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReduceDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReduceDone() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ReduceDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReduceDone(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReduceDone(::grpc::ServerContext* context, ::mapreduce::ReduceRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Map<WithAsyncMethod_Reduce<WithAsyncMethod_SubscribeReduceTask<WithAsyncMethod_SubscribeMapTask<WithAsyncMethod_MapDone<WithAsyncMethod_ReduceDone<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Map() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mapreduce::MapRequest, ::mapreduce::MapResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mapreduce::MapRequest* request, ::mapreduce::MapResponse* response) { return this->Map(context, request, response); }));}
    void SetMessageAllocatorFor_Map(
        ::grpc::MessageAllocator< ::mapreduce::MapRequest, ::mapreduce::MapResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mapreduce::MapRequest, ::mapreduce::MapResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::mapreduce::MapResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Map(
      ::grpc::CallbackServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::mapreduce::MapResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Reduce() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mapreduce::ReduceRequest* request, ::mapreduce::ReduceResponse* response) { return this->Reduce(context, request, response); }));}
    void SetMessageAllocatorFor_Reduce(
        ::grpc::MessageAllocator< ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::mapreduce::ReduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reduce(
      ::grpc::CallbackServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::mapreduce::ReduceResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SubscribeReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubscribeReduceTask() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::google::protobuf::Empty, ::mapreduce::TaskNotification>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request) { return this->SubscribeReduceTask(context, request); }));
    }
    ~WithCallbackMethod_SubscribeReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeReduceTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::mapreduce::TaskNotification>* SubscribeReduceTask(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SubscribeMapTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubscribeMapTask() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::google::protobuf::Empty, ::mapreduce::TaskNotification>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request) { return this->SubscribeMapTask(context, request); }));
    }
    ~WithCallbackMethod_SubscribeMapTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMapTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::mapreduce::TaskNotification>* SubscribeMapTask(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_MapDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MapDone() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::mapreduce::MapRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mapreduce::MapRequest* request, ::google::protobuf::Empty* response) { return this->MapDone(context, request, response); }));}
    void SetMessageAllocatorFor_MapDone(
        ::grpc::MessageAllocator< ::mapreduce::MapRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mapreduce::MapRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_MapDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapDone(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MapDone(
      ::grpc::CallbackServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReduceDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReduceDone() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::mapreduce::ReduceRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mapreduce::ReduceRequest* request, ::google::protobuf::Empty* response) { return this->ReduceDone(context, request, response); }));}
    void SetMessageAllocatorFor_ReduceDone(
        ::grpc::MessageAllocator< ::mapreduce::ReduceRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mapreduce::ReduceRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReduceDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReduceDone(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReduceDone(
      ::grpc::CallbackServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Map<WithCallbackMethod_Reduce<WithCallbackMethod_SubscribeReduceTask<WithCallbackMethod_SubscribeMapTask<WithCallbackMethod_MapDone<WithCallbackMethod_ReduceDone<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Map() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::mapreduce::MapResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Reduce() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::mapreduce::ReduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubscribeReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubscribeReduceTask() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SubscribeReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeReduceTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubscribeMapTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubscribeMapTask() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_SubscribeMapTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMapTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_MapDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MapDone() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_MapDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapDone(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReduceDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReduceDone() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ReduceDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReduceDone(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Map() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::mapreduce::MapResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMap(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Reduce() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::mapreduce::ReduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReduce(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubscribeReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubscribeReduceTask() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SubscribeReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeReduceTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeReduceTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubscribeMapTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubscribeMapTask() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_SubscribeMapTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMapTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeMapTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_MapDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MapDone() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_MapDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapDone(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapDone(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReduceDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReduceDone() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_ReduceDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReduceDone(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReduceDone(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Map() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Map(context, request, response); }));
    }
    ~WithRawCallbackMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::mapreduce::MapResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Map(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Reduce() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Reduce(context, request, response); }));
    }
    ~WithRawCallbackMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::mapreduce::ReduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reduce(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubscribeReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubscribeReduceTask() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->SubscribeReduceTask(context, request); }));
    }
    ~WithRawCallbackMethod_SubscribeReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeReduceTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* SubscribeReduceTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubscribeMapTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubscribeMapTask() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->SubscribeMapTask(context, request); }));
    }
    ~WithRawCallbackMethod_SubscribeMapTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMapTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* SubscribeMapTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MapDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MapDone() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MapDone(context, request, response); }));
    }
    ~WithRawCallbackMethod_MapDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapDone(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MapDone(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReduceDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReduceDone() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReduceDone(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReduceDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReduceDone(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReduceDone(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Map() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mapreduce::MapRequest, ::mapreduce::MapResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mapreduce::MapRequest, ::mapreduce::MapResponse>* streamer) {
                       return this->StreamedMap(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::mapreduce::MapResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMap(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mapreduce::MapRequest,::mapreduce::MapResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Reduce() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mapreduce::ReduceRequest, ::mapreduce::ReduceResponse>* streamer) {
                       return this->StreamedReduce(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::mapreduce::ReduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReduce(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mapreduce::ReduceRequest,::mapreduce::ReduceResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MapDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MapDone() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mapreduce::MapRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mapreduce::MapRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedMapDone(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MapDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MapDone(::grpc::ServerContext* /*context*/, const ::mapreduce::MapRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMapDone(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mapreduce::MapRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReduceDone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReduceDone() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mapreduce::ReduceRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mapreduce::ReduceRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedReduceDone(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReduceDone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReduceDone(::grpc::ServerContext* /*context*/, const ::mapreduce::ReduceRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReduceDone(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mapreduce::ReduceRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Map<WithStreamedUnaryMethod_Reduce<WithStreamedUnaryMethod_MapDone<WithStreamedUnaryMethod_ReduceDone<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_SubscribeReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_SubscribeReduceTask() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::google::protobuf::Empty, ::mapreduce::TaskNotification>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::google::protobuf::Empty, ::mapreduce::TaskNotification>* streamer) {
                       return this->StreamedSubscribeReduceTask(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_SubscribeReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubscribeReduceTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSubscribeReduceTask(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::google::protobuf::Empty,::mapreduce::TaskNotification>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_SubscribeMapTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_SubscribeMapTask() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::google::protobuf::Empty, ::mapreduce::TaskNotification>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::google::protobuf::Empty, ::mapreduce::TaskNotification>* streamer) {
                       return this->StreamedSubscribeMapTask(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_SubscribeMapTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubscribeMapTask(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::grpc::ServerWriter< ::mapreduce::TaskNotification>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSubscribeMapTask(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::google::protobuf::Empty,::mapreduce::TaskNotification>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_SubscribeReduceTask<WithSplitStreamingMethod_SubscribeMapTask<Service > > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Map<WithStreamedUnaryMethod_Reduce<WithSplitStreamingMethod_SubscribeReduceTask<WithSplitStreamingMethod_SubscribeMapTask<WithStreamedUnaryMethod_MapDone<WithStreamedUnaryMethod_ReduceDone<Service > > > > > > StreamedService;
};

}  // namespace mapreduce


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_MapReduce_2eproto__INCLUDED
